# 인공 신경망(Artificial Neural Networks)

우리가 정보를 어떻게 처리하고 학습하는지 궁금해 본 적이 있습니까? 예를 들어, 우리 몸은 손이나 다리를 움직일 수 있도록 정보를 어떻게 처리할까요? 간단하게 말하면 뇌에서 정보를 처리한 다음 몸의 다른 부분으로 신호를 보내 특정 근육의 움직임을 유도합니다. 이 신호는 신경계를 통해 전달됩니다. 신경계의 주요 구성 요소 중 하나는 뉴런 세포입니다. 이 세포들은 신호가 특정 값 또는 양보다 높은 경우에만 다른 세포로 신호를 전송합니다. 즉, 임계값을 기준으로 작동합니다. 따라서 우리가 손을 움직이기로 결정하면, 뇌의 신호는 다리 근육이 아닌 손 근육으로 뉴런 세포들을 통해 신호를 전달합니다.

### 인공신경망 훈련

그러나 이것은 우리가 정보를 처리하는 방법에 대해서만 설명해 줍니다. 인간의 학습 능력은 어떻게 작동하나요? 예를 들어, 우리는 빨간불에 멈춰서야 한다는 것을 알고 있고, 공을 차는 방법을 알고 있습니다. 다른 사람들이 하는 방법이나 사례를 보고 그렇게 하도록 훈련되었기 때문입니다. 이러한 예들을 통해 우리는 배우고 기억할 수 있었습니다.

컴퓨터가 인간이 정보를 처리하고 학습하는 방식을 모방할 수 있다면 얼마나 좋을까요? 인공 신경망으로 이것이 가능합니다! 인공 신경망은 데이터 세트 내에서 복잡한 관계를 처리하고 '학습'할 수 있습니다. 간단한 신경망의 개념도는 아래와 같습니다.

기본 아이디어는 입력 레이어(input layer)에 데이터를 입력하고, 뒤의 은닉 레이어(hidden layer)에서 데이터를 처리한다는 것입니다. 아래 그림에서 은닉 레이어가 하나만 표시되어 있지만 여러개의 은닉 레이어로 구성될 수  있습니다. 각 레이어는 데이터에 기능을 적용하고 다른 은닉 레이어로 전달한 후 최종적으로 출력 레이어(Output layer)로 끝나는 여러 개의 인공 뉴런으로 구성됩니다.

<img src = "resources/ANN.png">

위의 그림은 1개의 입력 레이어, 1개의 은닉 레이어(입력 레이어와 출력 레이어 사이) 및 1개의 출력 레이어로 구성된 간단한 신경망을 보여줍니다. 각 원은 1개의 노드 또는 1개의 뉴런을 나타냅니다. 입력 레이어는 모델에 전달되는 데이터일 뿐이므로 일반적으로 모델 아키텍처에서 입력 레이어의 노드 수는 이야기하지 않습니다. 위의 신경망 모델의 은닉 레이어는 2개의 노드/뉴런이 있고 출력 레이어에는 1개의 노드/뉴런이 있습니다.

출력 레이어는 신경망의 결과를 출력합니다.

신경망은 어떻게 작동합니까? 기계 학습 프로젝트에 어떻게 유용할 수 있습니까? 인공 신경망에 대해 자세히 알아보려면 이 [동영상](https://www.youtube.com/watch?v=aircAruvnKk) 을 시청하세요. 영상을 일시 중지하고 신경망이 어떻게 작동하는지 이해하는 시간을 가져보세요. 워크시트에 신경망에 대해 흥미로운 정보를 기록해 두십시오. 5개의 노드가 가진 1개의 입력 레이어, 각각 3개의 노드가 있는 2개의 은닉 레이어, 2개의 노드가 있는 1개의 출력 레이어로 구성된 네트워크 그려보세요.

In [ ]:
# your answer here

# 신경망 훈련

인공 신경망의 다양한 기능을 이해한 후에도 여전히 남아 있는 한 가지 의문점은 네트워크가 "학습"하는 방법입니다.

3점 슛을 배우는 젊은 농구 선수를 생각해 봅시다. 슛을 하고 슛이 너무 짧아서 실패하면 농구 선수는 다음 슛의 강도를 높여서 거리감을 조정합니다. 다음 슛이 골대에서 너무 오른쪽으로 간다면 선수는 다음 슛이 골대 중앙을 향해 갈 수 있도록 방향을 조정합니다. 선수는 슛이 성공할 때까지 이 동작을 계속합니다. 이후 선수는 3점 슛을 쏠 때 성공했던 상황의 힘과 방향을 기억합니다.

이것은 신경망이 훈련되는 방식과 유사합니다. 먼저 데이터가 네트워크를 통해 전달되고 예측된 출력이 제공됩니다. 이것을 순전파라고 합니다. 그런 다음 예측된 출력은 데이터의 실제 출력과 비교되고, 예측 출력과 실제 출력의 차이는 모델을 통해 뒤로 전달됩니다. 역방향으로 전파 동안 예측 출력과 실제 출력 간의 차이가 줄어들도록 모델 내에서 조정이 이루어집니다. 이것을 역전파라고 합니다. 조정이 이루어진 후, 데이터는 입력 레이어에서 다시 전달되고 또 순전파를 통해 다른 예측된 출력이 만들어집니다. 새로운 예측 출력은 실제 출력과 다시 비교되고 그 차이는 모델을 통해 역방향으로 다시 전달됩니다. 모델 내에서 더 많은 조정이 이루어지게 됩니다.

예측 출력과 실제 출력의 차이가 최소화될 때까지 순전파와 역전파의 과정을 반복합니다. 최종적으로 모델이 학습되어 다른 유사한 데이터 세트의 예측에 사용할 수 있습니다.

신경망이 훈련되는 방식과 비슷한 생활 속의 또 다른 예를 찾아볼 수 있습니까?

In [ ]:
# your answer here

신경망을 조금 더 이해할 수 있도록 다른 예를 살펴봅시다. 여러분은 아버지의 생일을 맞이하여 생일 케이크를 만드는 임무를 부여받았습니다. 요리책을 보고 기본적인 케이크를 만들 수 있습니다. 여러분은 지금까지 먹어본 케이크 중 가장 맛있는 케이크가 되길 바라는 마음에 엄마에게 시식을 부탁하러 갑니다. 여러분의 어머니는 케이크가 너무 달고 약간 탄거 같다고 대답합니다. 여러분은 다시 케이크를 만들면서 설탕의 양과 오븐에서 굽는 시간을 조정하려고 노력합니다. 새로운 레시피와 베이킹 시간으로 또 다른 케이크를 만든 다음에 어머님께 다시 맛 테스트를 요청할 것입니다. 이것은 여러분이 완벽한 케이크를 만들 때까지 계속될 것입니다.

케이크를 굽는 첫 번째 단계는 인공 신경망 내에서 순전파 단계와 유사합니다. 어머니의 맛 테스트는 예상 출력과 실제 출력을 비교하는 것과 유사합니다. 설탕의 양과 베이킹 시간을 조정하는 것은 신경망 내에서 역전파와 유사합니다. 단계의 반복은 모델의 전체 학습 프로세스와 유사합니다.

역전파의 작동 방식을 시각적으로 잘 이해하려면 이 [동영상](https://www.youtube.com/watch?v=Ilg3gGewQ5U) 을 보고 관심 있는 정보를 모두 기록해 두십시오.

<font color=blue>보너스: 모델 내에서 조정되는 방법을 이해할 필요는 없습니다. 그러나 수학적으로 관심이 있거나 모든 조정을 이해하는 데 정말로 관심이 있고 시간이 있다면 아래 나열된 2개의 동영상을 시청해 보세요. 워크시트나 아래 셀에 관심있는 정보를 기록해 두십시오. </font>
- [동영상 1](https://www.youtube.com/watch?v=IHZwWFHWa-w)
- [동영상 2](https://www.youtube.com/watch?v=tIeHLnjs5U8)

In [ ]:
# your answer here

# Iris Flower 데이터 세트를 이용한 신경망 훈련

Iris Flower 데이터 세트를 사용하여 신경망을 훈련시켜 봅시다!

## 1. 필수 라이브러리 가져오기
먼저 필요한 라이브러리를 가져옵니다. pandas 및 numpy는 데이터 구조를 제공하고 scikit은 인공 신경망에 액세스하는 방법을 배울 수 있습니다.

In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

<img src = "./resources/PetalSepal1.png">

## 2. 데이터 세트 획득 및 탐색

Iris Flower 데이터 세트를 아래의 데이터 프레임 df로 가져옵니다.
파일은 iris.data 입니다.

모든 열의 헤더를 포함하는 것을 잊지 마십시오.

변수를 이해하려면 위의 그림(출처: https://www.researchgate.net/Figure/Trollius-ranunculoide-flower-with-measured-traits_fig6_272514310) 을 참조하십시오.

먼저 데이터를 탐색하겠습니다. 데이터 탐색이 어떻게 진행되었는지 기업하십니까?

1. csv 파일을 열고 데이터 프레임에 넣습니다.
2. 헤더를 포함합니다
3. .info() 및 .describe()를 사용하여 데이터 세트에 대한 기본 정보를 확인합니다.

누락된 값이나 오류 데이터가 있는지 확인합니다. 누락된 데이터가 있습니까?

In [24]:
df = pd.read_csv("[Dataset]_Module_18_(iris).data",header=None)
names = ["sepal_length", "sepal_width","petal_length", "petal_width", "class"]
df.columns = names
print(df.head())
print(df.info())
print(df.describe())

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean

## 3. 특성 및 목표 값 결정

이제 데이터 세트를 x 값(모델이 관계를 학습할 수 있는 특성)과 y 값(목표 값 또는 모델의 예상 출력)으로 분할해야 합니다.

### 표준화
데이터 세트도 표준화해야 합니다.
표준화의 용도는 무엇입니까? 이를 이해하려면 위의 데이터 분포를 살펴보십시오! 특성 데이터들은 서로 다른 평균과 표준 편차를 가지고 있습니다.이러한 변수를 비교하는 것은 어렵습니다. 표준화는 이러한 특성 데이터 들의 평균과 표준 편차를 균등화하여 쉽게 비교할 수 있도록 도와줍니다.

scikit-learn 라이브러리의 스케일링 관련 [자료](http://benalexkeen.com/feature-scaling-with-scikit-learn/) 를 참조하십시오. 스케일링 전후에 데이터가 어떻게 변경되었는지 확인하십시오.

이는 신경망이 쉽게 분류 작업을 할 수 있도록 하기 위한 것입니다. 아래 코드는 x 값을 x_value로 추출하고 표준화합니다. y_values는 나중에 추출합니다. 아래 코드를 실행하세요!

In [3]:
x_values = df[['sepal_length','sepal_width','petal_length','petal_width']]
print(x_values.head())
standardise = StandardScaler() # 표준척도는 분포의 평균값이 0이고 표준편차가 1이 되도록 데이터를 변환합니다.
x_values = standardise.fit_transform(x_values)
x_values_df = pd.DataFrame(x_values)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


표준화된 데이터 세트를 원본 데이터세트와 비교합니다.

In [4]:
print(x_values_df.head())

          0         1         2         3
0 -0.900681  1.032057 -1.341272 -1.312977
1 -1.143017 -0.124958 -1.341272 -1.312977
2 -1.385353  0.337848 -1.398138 -1.312977
3 -1.506521  0.106445 -1.284407 -1.312977
4 -1.021849  1.263460 -1.341272 -1.312977


.describe 함수를 사용하여 표준화된 데이터 세트의 현재 평균과 표준 값을 확인해 보세요!

In [5]:
print(x_values_df.describe())

                  0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -2.775558e-16 -5.140333e-16  1.154632e-16  9.251859e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.438987e+00 -1.568735e+00 -1.444450e+00
25%   -9.006812e-01 -5.877635e-01 -1.227541e+00 -1.181504e+00
50%   -5.250608e-02 -1.249576e-01  3.362659e-01  1.332259e-01
75%    6.745011e-01  5.692513e-01  7.627586e-01  7.905908e-01
max    2.492019e+00  3.114684e+00  1.786341e+00  1.710902e+00


## 4. 신경망 구축

이제 간단한 신경망을 구축해 봅시다. 그러기 위해서 keras 라이브러리에서 Dense와 Sequential 함수를 가져와야 합니다.

### Sequential
Sequential 모델을 사용하면 먼저 빈 모델 객체를 만든 다음 레이어를 순서대로 차례로 추가할 수 있습니다.

### Dense
Dense 레이어는 간단히 신경망의 뉴런 레이어라고 생각하면 됩니다.

In [25]:
# !pip install keras
# !pip install tensorflow

from keras.models import Sequential
from keras.layers import Dense     # 인공 신경망의 층임

입력 레이어 1개, 은닉 레이어 2개, 출력 레이어 1개로 신경망을 구축해 보겠습니다. 
은닉 레이어 내에 몇 개의 노드가 있어야 하는지를 결정하는 규칙은 없습니다. 이 신경망의 경우 각 은닉 레이어에 6개의 노드를 사용합니다.

출력 레이어는 클래스 수만큼 노드를 사용해야 합니다. iris 데이터 세트의 경우 출력 레이어에 몇 개의 노드를 사용해야 합니까?

In [ ]:
# your answer here

우리가 만드는 신경망을 그려보세요.

In [ ]:
# draw your neural network!

인공 신경망을 구축하기 위해 아래 코드를 실행해보세요.

In [10]:
# 신경망 모델을 초기화
model = Sequential()

# 6개의 노드가 있는 첫 번째 은닉 레이어를 추가합니다.
# Input_dim은 x_values 또는 입력 레이어의 수/특성 수를 나타냅니다.
# activation은 노드/뉴런이 활성화되는 방식을 나타냅니다. 우리는 relu를 사용할 것입니다. 다른 일반적인 활성화 방식은'sigmoid' 및 'tanh'입니다.
model.add(Dense(6, input_dim=4, activation='relu')) # 인공신경망 1번째 층

# 6개의 노드가 있는 두 번째 은닉 레이어를 추가합니다. 
model.add(Dense(6, activation='relu')) # 인공신경망 2번째 층

# 3개의 노드가 있는 출력 레이어를 추가합니다.
# 사용된 activation은 'softmax'입니다. Softmax는 범주형 출력 또는 대상을 처리할 때 사용됩니다.
model.add(Dense(3,activation='softmax')) # 인공신경망 3번째 층

# 모델을 컴파일합니다. optimizer는 모델 내에서 조정하는 방법을 의미합니다. loss은 예측된 출력과 실제 출력 간의 차이를 나타냅니다.
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy']) # 분류는 entropy, 회귀는 ? 

선택 사항: [활성화 함수 간의 비교](http://www.machineintellegence.com/different-types-of-activation-functions-in-keras/)

이전 Acquire-CV에서 ReLu에 대해 학습하였습니다. 더 많은 활성화 함수가 있습니다. 특정 데이터/입력이 뉴런을 따라갈 수 있도록 하는 [on-off 버튼](https://en.wikipedia.org/wiki/Activation_function) 과 같습니다. 지금은 이 함수에 대하여 자세히 알 필요는 없습니다.

컴파일된 후에 모델의 요약된 정보를 출력할 수 있습니다. 아래 코드를 실행하여 확인하세요.
- 모델의 레이어와 순서
- 각 레이어의 출력 형태
- 각 레이어의 매개변수(가중치) 수
- 모델의 총 매개변수(가중치) 수

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 30        
                                                                 
 dense_4 (Dense)             (None, 6)                 42        
                                                                 
 dense_5 (Dense)             (None, 3)                 21        
                                                                 
Total params: 93 (372.00 Byte)
Trainable params: 93 (372.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


y_values는 원래 범주형 데이터이므로(숫자 대신 꽃 이름) 신경망을 훈련시키기 전에 범주의 y_value를 숫자로 변환하는 작업을해야 합니다. 신경망의 경우 범주가 숫자 그룹(예: 1,2,3,4 등)이 아닌 경우 원-핫 인코딩을 수행하기 전에 라벨 인코딩(이전 노트북을 참조하세요)을 먼저 수행해야 합니다.

원-핫 인코딩에 대한 자세한 내용은 "지도 학습 기술" 노트북의 보너스 섹션을 참조하십시오. 이 [문서](https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/) 에서 더 자세히 알아볼 수도 있습니다. Keras의 to_categorical 함수를 사용하여 진행할 수 있습니다. 아래 코드를 실행하여 라벨 인코딩을 한 다음 y_values를 원-핫 인코딩하십시오.

In [12]:
#from keras.utils import to_categorica
from tensorflow.keras.utils import to_categorical

# 각 클래스의 데이터 포인트 수 출력
print(df['class'].value_counts())

# 각기 다른 클래스에 대하여 다른 숫자를 지정한 딕셔너리
# 원-핫 인코딩으로 4개 열이 아닌 3개 열만 생성되도록 0부터 시작하는 값을 사용합니다.
label_encode = {"class": {"Iris-setosa":0, "Iris-versicolor":1, "Iris-virginica":2}}

# .replace를 사용하여 다른 클래스를 숫자로 변경
df.replace(label_encode,inplace=True)

# 각 클래스의 데이터 포인트 수를 출력하여 클래스가 숫자로 변경되었는지 확인
print(df['class'].value_counts())

# 클래스를 y_values로 추출
y_values = df['class']

# y_values 원-핫 인코딩
y_values = to_categorical(y_values) # Categorical은 Pandas의 getdummies와 같음

print(y_values)
y_values

0    50
1    50
2    50
Name: class, dtype: int64
0    50
1    50
2    50
Name: class, dtype: int64
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

위의 y_values에 나열된 내용을 확인하세요. 꽃 이름을 숫자로 인코딩했습니다.

이제 모델을 훈련시켜 봅시다. 아래 코드를 실행하세요!

In [13]:
# x_values와 y_values로 모델을 훈련시킵니다.
# Epoch는 전체 데이터 세트가 모델을 학습하는 데 사용되는 횟수를 나타냅니다.
# Shuffle = True는 모델이 각 Epoch 후에 데이터 세트의 배열을 무작위로 지정하도록 지시합니다.
model.fit(x_values,y_values,epochs=20,shuffle=True) # Epoch는 학습을 뜻함 

Epoch 1/20
5/5 [==============================] - 0s 3ms/step - loss: 1.0889 - accuracy: 0.3733
Epoch 2/20
5/5 [==============================] - 0s 0s/step - loss: 1.0723 - accuracy: 0.4133
Epoch 3/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0576 - accuracy: 0.4733
Epoch 4/20
5/5 [==============================] - 0s 2ms/step - loss: 1.0433 - accuracy: 0.5067
Epoch 5/20
5/5 [==============================] - 0s 612us/step - loss: 1.0281 - accuracy: 0.5200
Epoch 6/20
5/5 [==============================] - 0s 4ms/step - loss: 1.0135 - accuracy: 0.5733
Epoch 7/20
5/5 [==============================] - 0s 0s/step - loss: 1.0001 - accuracy: 0.6200
Epoch 8/20
5/5 [==============================] - 0s 1ms/step - loss: 0.9866 - accuracy: 0.6267
Epoch 9/20
5/5 [==============================] - 0s 3ms/step - loss: 0.9733 - accuracy: 0.6267
Epoch 10/20
5/5 [==============================] - 0s 0s/step - loss: 0.9595 - accuracy: 0.6400
Epoch 11/20
5/5 [=======================

축하합니다! 여러분의 첫 번째 신경망을 훈련했습니다. 정확도를 살펴보기 전에 사용되는 몇가지 용어를 이해해야 합니다.

- Epoch는 전체 데이터 세트가 모델을 학습하는 데 사용되는 횟수를 나타냅니다.

- us/step은 모델이 각 에포크에서 학습하는 데 걸린 시간을 보여줍니다.

- acc는 모델이 얼마나 정확한지 보여줍니다.

숫자가 각 epoch에 따라 어떻게 변경되는지 확인해 보세요.

위의 모델에서 얻은 정확도 값은 얼마입니까?

모델에 다른 은닉 레이어를 추가하여 더 나은 정확도를 얻을 수 있는지 확인하십시오. 
추가 은닉 레이어는 이전 레이어와 동일한 수의 노드를 가질 수 있습니다.

위에 나열된 관련 코드를 아래 셀에 복사하고 코드를 수정하여 은닉 레이어를 추가합니다. 새 모델을 훈련시키고 정확도가 향상되는지 확인합니다.

In [ ]:
# your code here

In [ ]:
# your code here

은닉 레이어를 추가한 후 정확도가 초기 모델보다 낮아졌습니다. 따라서 더 많은 레이어를 추가하는 것이 반드시 더 높은 정확도를 보장하는 것은 아닙니다.

<font color = blue>보너스: 정확도를 향상시키기 위해 은닉 레이어의 노드 숫자를 늘려볼 수 있습니다. 은닉 레이어의 노드 숫자를 늘리면 정확도가 개선이 되나요?</font>

In [ ]:
# your codehere

In [ ]:
# your code here

In [ ]:
# your answer here

# 검증 데이터세트

앞서 우리는 신경망이 여러 Epoch 동안 훈련될 수 있음을 알았습니다. 이는 네트워크가 동일한 데이터 세트로 여러 번 계속 학습할 수 있음을 의미합니다. 모델이 동일한 데이터 세트로 계속 학습하면 어떻게 될까요? 이러한 과정으로 네트워크의 정확도가 높아질 수 있을까요?

In [ ]:
# your answer here

모델이 계속 학습함에 따라 모델의 정확도가 증가할 것입니다. 동일한 데이터 세트로 시험해 볼 수 있습니다. 아래 코드를 실행하고 정확도를 관찰해 보세요. 동일한 설정으로 이전 모델보다 정확도가 높아졌습니까?

In [14]:
# 신경망 모델을 초기화
model4 = Sequential()

# 6개의 노드가 있는 첫 번째 은닉 레이어를 추가합니다.
# Input_dim은 x_values 또는 입력 레이어의 수/특성 수를 나타냅니다.
# activation은 노드/뉴런이 활성화되는 방식을 나타냅니다. 우리는 relu를 사용할 것입니다. 다른 일반적인 활성화 방식은'sigmoid' 및 'tanh'입니다.
model4.add(Dense(6,input_dim=4,activation='relu'))

# 6개의 노드가 있는 두 번째 은닉 레이어를 추가합니다. 
model4.add(Dense(6,activation='relu'))

# 3개의 노드가 있는 출력 레이어를 추가합니다.
# 사용된 activation은 'softmax'입니다. Softmax는 범주형 출력 또는 대상을 처리할 때 사용됩니다.
model4.add(Dense(3,activation='softmax'))

# 모델을 컴파일합니다. optimizer는 모델 내에서 조정하는 방법을 의미합니다. loss은 예측된 출력과 실제 출력 간의 차이를 나타냅니다.
model4.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# x_values와 y_values로 모델을 훈련시킵니다.
# Epoch는 전체 데이터 세트가 모델을 학습하는 데 사용되는 횟수를 나타냅니다.
# Shuffle = True는 모델이 각 Epoch 후에 데이터 세트의 배열을 무작위로 지정하도록 지시합니다.
model4.fit(x_values,y_values,epochs=200,shuffle=True)

Epoch 1/200
5/5 [==============================] - 0s 2ms/step - loss: 1.5254 - accuracy: 0.3333
Epoch 2/200
5/5 [==============================] - 0s 1ms/step - loss: 1.4912 - accuracy: 0.3333
Epoch 3/200
5/5 [==============================] - 0s 0s/step - loss: 1.4612 - accuracy: 0.3267
Epoch 4/200
5/5 [==============================] - 0s 4ms/step - loss: 1.4299 - accuracy: 0.3267
Epoch 5/200
5/5 [==============================] - 0s 4ms/step - loss: 1.4029 - accuracy: 0.3267
Epoch 6/200
5/5 [==============================] - 0s 4ms/step - loss: 1.3763 - accuracy: 0.3200
Epoch 7/200
5/5 [==============================] - 0s 0s/step - loss: 1.3526 - accuracy: 0.3200
Epoch 8/200
5/5 [==============================] - 0s 0s/step - loss: 1.3277 - accuracy: 0.3200
Epoch 9/200
5/5 [==============================] - 0s 0s/step - loss: 1.3038 - accuracy: 0.3267
Epoch 10/200
5/5 [==============================] - 0s 4ms/step - loss: 1.2817 - accuracy: 0.3533
Epoch 11/200
5/5 [===============

5/5 [==============================] - 0s 0s/step - loss: 0.3062 - accuracy: 0.9067
Epoch 86/200
5/5 [==============================] - 0s 4ms/step - loss: 0.3019 - accuracy: 0.9067
Epoch 87/200
5/5 [==============================] - 0s 4ms/step - loss: 0.2975 - accuracy: 0.9067
Epoch 88/200
5/5 [==============================] - 0s 0s/step - loss: 0.2929 - accuracy: 0.9067
Epoch 89/200
5/5 [==============================] - 0s 4ms/step - loss: 0.2886 - accuracy: 0.9133
Epoch 90/200
5/5 [==============================] - 0s 4ms/step - loss: 0.2842 - accuracy: 0.9133
Epoch 91/200
5/5 [==============================] - 0s 0s/step - loss: 0.2801 - accuracy: 0.9133
Epoch 92/200
5/5 [==============================] - 0s 0s/step - loss: 0.2760 - accuracy: 0.9133
Epoch 93/200
5/5 [==============================] - 0s 4ms/step - loss: 0.2722 - accuracy: 0.9133
Epoch 94/200
5/5 [==============================] - 0s 0s/step - loss: 0.2683 - accuracy: 0.9133
Epoch 95/200
5/5 [====================

5/5 [==============================] - 0s 0s/step - loss: 0.1230 - accuracy: 0.9733
Epoch 169/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1220 - accuracy: 0.9733
Epoch 170/200
5/5 [==============================] - 0s 0s/step - loss: 0.1209 - accuracy: 0.9733
Epoch 171/200
5/5 [==============================] - 0s 0s/step - loss: 0.1199 - accuracy: 0.9733
Epoch 172/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1190 - accuracy: 0.9733
Epoch 173/200
5/5 [==============================] - 0s 0s/step - loss: 0.1182 - accuracy: 0.9733
Epoch 174/200
5/5 [==============================] - 0s 0s/step - loss: 0.1171 - accuracy: 0.9733
Epoch 175/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1162 - accuracy: 0.9733
Epoch 176/200
5/5 [==============================] - 0s 0s/step - loss: 0.1153 - accuracy: 0.9733
Epoch 177/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1144 - accuracy: 0.9733
Epoch 178/200
5/5 [===========

정확도 점수가 이제 90% 이상임을 출력에서 확인할 수 있습니다. 에포크 수를 늘리는 것만으로도 정확도를 높일 수 있습니다. 모델이 훈련된 데이터에 대해서만 정확하다는 것이 좋다고 생각하십니까? 
축구 선수가 경기장의 특정 지점에서 골을 넣는 것만 연습한다면 경기에서도 좋은 결과를 얻을 수 있을까요? 제빵사가 특정한 맛, 모양, 크기의 케이크를 굽는 방법만 배운다면 고객의 요청에 따라 맛있는 케이크를 만들 수 있을까요?

축구 선수는 운동장의 다른 지역에서는 정확하게 슛을 쏘지 못할 수 있으므로 경기에서 좋은 결과를 얻기 어려울 수 있습니다. 제빵사는 한 가지 특정 맛만 알기 때문에 손님이 원하는 맛있는 케이크를 구울 수 없습니다.

이 질문의 이면에 있는 아이디어는 과적합에 대한 개념입니다. 모델이 과적합되면 새로운 데이터에 대하여 예측 성능이나 정확도가 떨어질 수 있습니다.

이것은 과적합의 개념이며 모든 기계 학습 기술에도 적용됩니다. 모델이 데이터 세트에 너무 정확하게 맞춰지면 훈련된 모델은 이전에 본 적이 없는 새로운 데이터에 대하여 일반화하여 사용할 수 없습니다. 따라서 우리는 일반적으로 보유하고 있는 데이터 세트의 일부에 대해서만 모델을 훈련하고 나머지는 모델이 과적합되었는지 확인하기 위해 테스트 또는 검증 데이터 세트로 유지해야 합니다. Epoch가 증가함에 따라 훈련 세트로 학습시키 모델의 테스트 세트의 정확도는 높아져야 합니다. 그러나 과적합 지점에서 테스트 세트의 정확도가 감소하기 시작합니다. 특정 Epoch 이후에 테스트 정확도가 증가하기 시작했다면 더 이상 모델을 훈련해서는 안 됩니다.

여기에서 사용하는 데이터 세트를 훈련 세트와 테스트 세트로 나누어 적용해 보겠습니다.

먼저, 모델이 학습에 노출되지 않고 유지할 데이터의 양을 결정해야 합니다. 일반적으로 전체 데이터의 20~30%를 테스트 세트로 유지합니다. 이 예에서는 데이터 세트의 25%를 테스트/검증 세트로 유지합니다. sklearn 라이브러리에서 train_test_split 함수를 합니다. 아래 코드를 실행해보세요.

In [15]:
from sklearn.model_selection import train_test_split

# 데이터 프레임 df에서 원래 x_values를 추출합니다.
# 표준화는 모델이 학습할 데이터에만 기반해야 하므로 x_values를 다시 추출해야 합니다.
# 따라서 표준화하기 전에 먼저 데이터를 분할해야 합니다.
x_values = df[['sepal_length','sepal_width','petal_length','petal_width']]

# Test_size=0.25는 전체 데이터의 25%가 x_test 및 y_test로 배정되면75%는 x_train 및 y_train에 배정됨을 나타냅니다.
# random_state=10은 아래 코드를 실행할 때마다 분할이 동일하도록 하는 데 사용됩니다.
# 분할은 매번 랜덤으로 하기 때문입니다. 동일한 random_state는 매번 동일하게 분할되도록 보장하는 유일한 방법입니다.
x_train, x_test, y_train, y_test = train_test_split(x_values,y_values,test_size=0.25,random_state=10)

# x_train, x_test, y_train 및 y_test의 행 수 확인
print("Number of rows in x_train:", x_train.shape[0])
print("Number of rows in x_test:", x_test.shape[0])
print("Number of rows in y_train:", y_train.shape[0])
print("Number of rows in y_test:", y_test.shape[0])

# 이제 x 값을 표준화할 수 있습니다.
# StandardScaler 초기화
standardise = StandardScaler()

# .fit_transform을 사용하여 x_train 값을 표준화합니다.
x_train = standardise.fit_transform(x_train)

# .transform을 사용하여 x_test 값을 표준화합니다.
# 표준화는 x_train과 같아야 하므로 데이터를 맞출 필요가 없습니다.
x_test = standardise.transform(x_test)

Number of rows in x_train: 112
Number of rows in x_test: 38
Number of rows in y_train: 112
Number of rows in y_test: 38


데이터 세트의 20%를 테스트/검증 세트로 유지하여 데이터 세트를 훈련 및 테스트/검증 세트로 분할하는 코드를 작성하십시오. 
x_train2, x_test2, y_train2 및 y_test2를 변수로 사용하십시오. 각 변수에 대한 행 수가 올바른지 확인하십시오.

In [ ]:
# your code/answer here

이제 x_train2, x_test2, y_train2 및 y_test2를 사용하여 신경망을 훈련시킵니다. 각각 6개의 노드가 있는 2개의 은닉 레이어와 3개의 노드가 있는 1개의 출력 레이어가 있는 신경망을 만드는 코드를 작성하십시오. 처음 은닉 레이어의 활성화(activation)는 'relu'인 반면 출력 레이어에 대한 활성화는 'softmax'입니다. 사용할 옵티마이저(optimizer)는 'adam'이고 손실(loss)은 'categorical_crossentropy'여야 합니다. 측정 항목(metrics)는 '정확도(accuracy)'입니다. model_val을 모델 변수로 사용하십시오. 모델을 컴파일한 후 모델 요약을 출력하십시오.

In [ ]:
# your code/answer here

이제 x_train 및 y_train을 사용하여 model_val을 훈련할 수 있습니다. 또한 x_test 및 y_test를 사용하여 각 에포크 후에 정확도를 테스트합니다. 아래 코드를 실행해보세요!

In [26]:
# x_values와 y_values로 모델을 훈련시킵니다.
# Epoch는 전체 데이터 세트가 모델을 학습하는 데 사용되는 횟수를 나타냅니다.
# Shuffle = True는 모델이 각 Epoch 후에 데이터 세트의 배열을 무작위로 지정하도록 지시합니다. 이렇게 하면 모델이 학습할 수 있습니다.
# Validation_data를 사용하면 테스트/검증 데이터 세트를 입력할 수 있습니다. 이를 통해 테스트/검증 세트에서 모델 정확도를 확인할 수 있습니다.
model_val.fit(x_train,y_train,epochs=50,shuffle=True, validation_data=(x_test,y_test))

NameError: name 'model_val' is not defined

출력에 검증 데이터의 정확도도 같이 표시되고 있습니다. 검증 정확도가 훈련 정확도보다 높은가요?아니면 낮은가요?

In [ ]:
# your answer here

또한 모델을 사용하여 새로 수집된 데이터의 꽃 유형을 식별할 수 있습니다. 예를 들어, 친구가 일부 꽃의 꽃받침 길이, 꽃받침 너비, 꽃잎 길이 및 꽃잎 너비를 측정하고 "iris_predict.data"라는 파일에 데이터를 저장했다고 가정해 봅시다. 친구가 측정된 값을 기반으로 이 꽃의 종류를 찾고 싶어합니다. 친구를 돕기 위해 분류 모델을 사용하여 친구가 찾은 꽃의 종류를 찾아보세요. 아래 코드를 실행해 보세요!
<font color=blue>힌트: model.predict 메서드를 사용하여 친구의 꽃 종류를 얻을 수 있습니다. 또한 .predict 메서드에서 반환된 값은 모델이 각 데이터 행에 할당해야 한다고 생각하는 각 꽃 유형의 확률입니다. 따라서 확률이 높을수록 모델이 예측한 꽃 유형이 정확하다는 확신을 가질 수 있습니다. 예를 들어 예측 값이 두 번째 열에서 매우 높으면 모델은 꽃 유형이 versicolor라고 생각할 수 있습니다. 또한 꽃 유형을 얻기 전에 데이터를 스케일링해야 합니다. </font>

In [17]:
df2 = pd.read_csv("[Dataset]_Module_18_(iris).data",header=None)
names = ["sepal_length", "sepal_width","petal_length", "petal_width","class"]
df2.columns = names

In [18]:
x_new = df2[['sepal_length','sepal_width','petal_length','petal_width']]

In [19]:
x_new_scale = standardise.transform(x_new)

In [20]:
y_new = model_val.predict(x_new_scale)

NameError: name 'model_val' is not defined

In [21]:
print(y_new)

NameError: name 'y_new' is not defined

각 데이터 행의 꽃 유형은 무엇입니까? [argmax](https://www.geeksforgeeks.org/numpy-argmax-python/) 함수를 사용하여 y_new에서 꽃 종류를 식별할 수 있습니다. 아래 코드를 실행해보세요!

In [ ]:
flower_types = []
for ii in range(0,y_new.shape[0]):
    flower_types.append(np.argmax(y_new[ii,:]))
print(flower_types)

번호로 표기된 꽃의 유형을 다시 원래의 클래스 정보(Setosa, Versicolor, Virginica)로 변경할 수 있습니까?

In [ ]:
# your answer here

축하합니다! 인공 신경망 모델을 만들고 훈련하는 방법을 성공적으로 배웠습니다. 인공 신경망은 매우 큰 데이터 세트에 사용할 수 있는 매우 강력한 도구입니다. 예를 들어, 수백 개의 열/특성과 100,000개 이상의 데이터 포인트가 있는 경우 다른 기계 학습 기술 대신 인공 신경망을 사용하는 것이 유리할 수 있습니다. 은닉 레이어 노드 수 또는 은닉 레이어 수에 대한 엄격한 규칙은 없습니다. 다양한 신경망을 실험하여 데이터 세트에 가장 적합한 결과를 제공하는 신경망을 찾는 것이 중요합니다.